name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy files to Hetzner
        uses: appleboy/scp-action@master
        with:
          host: 178.104.70.62
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          source: "."
          target: "/var/www/lumina"
